# ConfigMap for API URLs and Redis/Database Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-config
data:
  VITE_AUTH_API_URL: "https://district12.xyz/auth"
  VITE_PAYMENT_API_URL: "https://district12.xyz/pay"
  VITE_DOWNLOAD_API_URL: "https://district12.xyz/down"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: QVZOU19XdW5kSDhpM2hIdFZJblRLZFhr