# Horizontal Pod Autoscaler for train-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: train-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tick12-train-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80